#!/bin/bash

#SBATCH --gres=gpu:1
#SBATCH --ntasks=8
#SBATCH --mem=32G
#SBATCH --time=3-00:00


# input parameters:
#  $1 -> predictor type
#  $2 -> algnameaddition
#  $3 -> whether uncertainties are used
#  $4 -> dimension


# ----------------------------------------------------------------------------
# sphere, rastrigin, rosenbrock

#functions=(sphere rastrigin rosenbrock)
#poschgt="sinefreq"
#n=0.00
#for f in "${functions[@]}"

# ----------------------------------------------------------------------------
# MPB

f="mpbcorr"
poschgt="none"
noises=(0.00 0.01 0.05)


# ----------------------------------------------------------------------------



for n in "${noises[@]}"
do
	./run_server.sh "$1" "$2" "$3" "$4" "$f" "$poschgt" "$n"&
done

wait
